package frc.robot.commands.autos;

import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.path.PathPlannerPath;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.subsystems.SuperSystem;
import frc.robot.subsystems.swerve.SwerveDrivetrain;
import frc.robot.subsystems.vision.NoteAssistance;

public class BatteryTestingAuto extends SequentialCommandGroup{ 
        public BatteryTestingAuto(SwerveDrivetrain swerve, SuperSystem superSystem, NoteAssistance na, double targetNoteArea, int minSamples, int maxSamples, PathPlannerPath path0) {
        Pose2d startingPose = new Pose2d(2, 6.5, new Rotation2d());

        addCommands(
            Commands.runOnce(() -> swerve.resetGyroFromPoseWithAlliance(startingPose)),
            Commands.runOnce(() -> swerve.resetOdometryWithAlliance(startingPose)),

            Commands.sequence(
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ), 
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ), 
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ), 
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ), 
                    AutoBuilder.followPath(path0),//c26
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootSubwoofer()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.intakeBasic()
                        )
                    ),
                    AutoBuilder.followPath(path0),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(2),
                            superSystem.shootAmp()
                        )
                    ),
                    Commands.deadline(
                        Commands.race(
                            Commands.waitSeconds(1.5),
                            superSystem.stow()
                        )
                    )
            )
                    
                    
        );
        
}
}